# Generated by Django 5.0.6 on 2024-06-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
