# Generated by Django 5.0.6 on 2024-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
